/**
 * Renders `templates/qa-metrics-dashboard.html` to:
 *   - artifacts/qa-metrics-dashboard.pdf       (printable report)
 *   - artifacts/qa-metrics-dashboard.live.html (self-contained snapshot)
 * using the Playwright Chromium that's already installed in this repo.
 *
 * Usage:
 *   npx tsx scripts/export-dashboard-pdf.ts
 *   # or
 *   npm run export:dashboard
 */
import { chromium, type Page } from '@playwright/test';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

interface Sources {
  summary: string | null;
  trend:   string | null;
  defects: string | null;
}

interface Paths {
  htmlPath: string;
  artifactsDir: string;
  pdfPath: string;
  summaryJsonPath: string;
  trendJsonPath: string;
  defectsJsonPath: string;
}

function buildPaths(repoRoot: string): Paths {
  const artifactsDir = resolve(repoRoot, 'artifacts');
  return {
    htmlPath:        resolve(repoRoot, 'templates/qa-metrics-dashboard.html'),
    artifactsDir,
    pdfPath:         resolve(artifactsDir, 'qa-metrics-dashboard.pdf'),
    summaryJsonPath: resolve(repoRoot, 'reports/run-summary.json'),
    trendJsonPath:   resolve(repoRoot, 'reports/run-trend.json'),
    defectsJsonPath: resolve(repoRoot, 'reports/defects.json'),
  };
}

function resolveSources(p: Paths): Sources {
  const toUrl = (filePath: string): string | null =>
    existsSync(filePath) ? pathToFileURL(filePath).toString() : null;

  const sources: Sources = {
    summary: toUrl(p.summaryJsonPath),
    trend:   toUrl(p.trendJsonPath),
    defects: toUrl(p.defectsJsonPath),
  };

  console.log(sources.summary
    ? `▸ Using live data: ${p.summaryJsonPath}`
    : '▸ No reports/run-summary.json yet — using static fallback data.');
  console.log(sources.defects
    ? `▸ Using defect data: ${p.defectsJsonPath}`
    : '▸ No reports/defects.json yet — using static defect data. Run `npm run fetch:defects`.');

  return sources;
}

async function injectSourceUrls(page: Page, sources: Sources): Promise<void> {
  await page.addInitScript(
    ({ summary, trend, defects }: Sources) => {
      const g = globalThis as unknown as {
        __SUMMARY_URL__?: string; __TREND_URL__?: string; __DEFECTS_URL__?: string;
      };
      if (summary) g.__SUMMARY_URL__ = summary;
      if (trend)   g.__TREND_URL__   = trend;
      if (defects) g.__DEFECTS_URL__ = defects;
    },
    sources,
  );
}

async function renderPdf(page: Page, p: Paths): Promise<void> {
  const url = pathToFileURL(p.htmlPath).toString();
  console.log(`▸ Rendering ${url}`);

  await page.goto(url, { waitUntil: 'networkidle' });
  await page.waitForFunction(
    () => (globalThis as unknown as { __DASHBOARD_READY__?: boolean }).__DASHBOARD_READY__ === true,
    undefined,
    { timeout: 10_000 },
  );

  // Chart.js animations end ~1s after render; wait a beat to avoid mid-frame capture.
  await page.waitForTimeout(1200);
  await page.emulateMedia({ media: 'print' });
  await page.pdf({
    path: p.pdfPath,
    format: 'A4',
    printBackground: true,
    preferCSSPageSize: true,
    margin: { top: '12mm', right: '14mm', bottom: '12mm', left: '14mm' },
  });
  console.log(`✓ Wrote ${p.pdfPath}`);
}

function emitLiveSnapshot(p: Paths, sources: Sources): void {
  if (!sources.summary && !sources.trend && !sources.defects) {
    console.log('▸ Skipped .live.html snapshot — no run/defect JSON to inline.');
    return;
  }

  // Self-contained snapshot HTML with the JSON inlined as base64 `data:` URLs.
  // Anyone can open this file directly in a browser (no local server needed,
  // no CORS errors on file://) and see the latest numbers. The original
  // templates/qa-metrics-dashboard.html stays a clean template so git diffs
  // only show real changes.
  const toDataUrl = (filePath: string, isPresent: string | null): string =>
    isPresent ? `data:application/json;base64,${readFileSync(filePath).toString('base64')}` : '';

  const summaryDataUrl = toDataUrl(p.summaryJsonPath, sources.summary);
  const trendDataUrl   = toDataUrl(p.trendJsonPath,   sources.trend);
  const defectsDataUrl = toDataUrl(p.defectsJsonPath, sources.defects);

  const inlineLines = [
    `/* Auto-generated by scripts/export-dashboard-pdf.ts at ${new Date().toISOString()}. */`,
    '/* Data URLs are inlined so the file works on file:// without a server. */',
    summaryDataUrl ? `globalThis.__SUMMARY_URL__ = ${JSON.stringify(summaryDataUrl)};` : '',
    trendDataUrl   ? `globalThis.__TREND_URL__ = ${JSON.stringify(trendDataUrl)};`     : '',
    defectsDataUrl ? `globalThis.__DEFECTS_URL__ = ${JSON.stringify(defectsDataUrl)};` : '',
  ].filter(Boolean).join('\n    ');

  const liveHtmlPath = resolve(p.artifactsDir, 'qa-metrics-dashboard.live.html');
  const injection    = `\n  <script>\n    ${inlineLines}\n  </script>\n</head>`;
  const snapshot     = readFileSync(p.htmlPath, 'utf8').replace('</head>', injection);
  writeFileSync(liveHtmlPath, snapshot);
  console.log(`✓ Wrote ${liveHtmlPath}`);
}

async function main(): Promise<void> {
  const repoRoot = resolve(__dirname, '..');
  const paths    = buildPaths(repoRoot);

  if (!existsSync(paths.htmlPath)) {
    throw new Error(`Source HTML not found: ${paths.htmlPath}`);
  }
  mkdirSync(paths.artifactsDir, { recursive: true });

  const sources = resolveSources(paths);

  const browser = await chromium.launch();
  try {
    const context = await browser.newContext({
      viewport: { width: 1280, height: 1800 },
      deviceScaleFactor: 2,
    });
    const page = await context.newPage();
    await injectSourceUrls(page, sources);
    await renderPdf(page, paths);
    emitLiveSnapshot(paths, sources);
  } finally {
    await browser.close();
  }
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
